// ajax and loading actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Auth actions
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';

// User actions
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_IS_ADMIN_SUCCESS = 'USER_IS_ADMIN_SUCCESS';

// Chat rooms actions
export const CHAT_GET_ROOMS_SUCCESS = 'CHAT_GET_ROOMS_SUCCESS';

export const CHAT_STORE_TEMPORARY_ROOM = 'CHAT_STORE_TEMPORARY_ROOM';

export const CHAT_CREATE_ROOM_SUCCESS = 'CHAT_CREATE_ROOM_SUCCESS';

export const CHAT_ACCESS_ROOM = 'CHAT_ACCESS_ROOM';
export const CHAT_ACCESS_ROOM_SUCCESS = 'CHAT_ACCESS_ROOM_SUCCESS';

export const CHAT_LEAVE_ROOM = 'CHAT_LEAVE_ROOM';
export const CHAT_LEAVE_ROOM_SUCCESS = 'CHAT_LEAVE_ROOM_SUCCESS';

// Chat actives users actions
export const CHAT_GET_ACTIVE_USER_SUCCESS = 'CHAT_GET_ACTIVE_USER_SUCCESS';
export const CHAT_REMOVE_ACTIVE_USERS = 'CHAT_REMOVE_ACTIVE_USERS';
export const CHAT_ADD_CURRENT_USER_ACTIVE_ID = 'CHAT_ADD_CURRENT_USER_ACTIVE_ID';
export const CHAT_REMOVE_CURRENT_USER_ACTIVE_ID = 'CHAT_REMOVE_CURRENT_USER_ACTIVE_ID';

// Chat messages actions
export const CHAT_GET_MESSAGE_SUCCESS = 'CHAT_GET_MESSAGE_SUCCESS';

export const CHAT_GET_LAST_MESSAGES_SUCCESS = 'CHAT_GET_LAST_MESSAGES_SUCCESS';
export const CHAT_REMOVE_MESSAGES = 'CHAT_REMOVE_MESSAGES';

export const CHAT_STORE_TEMPORARY_MESSAGE = 'CHAT_STORE_TEMPORARY_MESSAGE';

export const CHAT_SEND_MESSAGE_SUCCESS = 'CHAT_SEND_MESSAGE_SUCCESS';

// Chat users actions
export const CHAT_GET_USERS_SUCCESS = 'CHAT_GET_USERS_SUCCESS';
