// ajax and loading actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Auth actions
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';

// User actions
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_IS_ADMIN_SUCCESS = 'USER_IS_ADMIN_SUCCESS';

// Chat actions
export const CHAT_GET_ROOMS_SUCCESS = 'CHAT_GET_ROOMS_SUCCESS';

export const CHAT_STORE_TEMPORARY_MESSAGE = 'CHAT_STORE_TEMPORARY_MESSAGE';

export const CHAT_SEND_MESSAGE = 'CHAT_SEND_MESSAGE';
export const CHAT_SEND_MESSAGE_SUCCESS = 'CHAT_SEND_MESSAGE_SUCCESS';
export const CHAT_SEND_MESSAGE_ERROR = 'CHAT_SEND_MESSAGE_ERROR';

export const CHAT_GET_LAST_MESSAGES = 'CHAT_GET_LAST_MESSAGES';
export const CHAT_GET_LAST_MESSAGES_SUCCESS = 'CHAT_GET_LAST_MESSAGES_SUCCESS';
export const CHAT_GET_LAST_MESSAGES_ERROR = 'CHAT_GET_LAST_MESSAGES_ERROR';

export const CHAT_GET_USERS_SUCCESS = 'CHAT_GET_USERS_SUCCESS';
